### ISSUE TITLE
[REQ]WIJ WILLEN EEN KNOPJE

### ISSUE THREAD

**Issue by Jazzkuh** [MinetopiaSDB/wiki#1]
**Wat is je idee?**
Knopje
**Waarom moet dit toegevoegd worden?**
Omdat knopje handig is
**Heb je gecontroleerd of dit nog niet eerder aangevraagd is?**
Ja, knopje!

**Comment by Codixer** [comment]
Meer info geven

**Comment by LittleDraily** [comment]
welk knopje

**Comment by Jazzkuh** [comment]
schuifje

**Comment by LittleDraily** [comment]
wat doet het

**Comment by Codixer** [comment]
wat voor schuifje

**Comment by Jazzkuh** [comment]
vierkant

**Comment by Codixer** [comment]
WAT DOET HET

**Comment by LittleDraily** [comment]
oke doen we maak jij de pr?

**Comment by LittleDraily** [comment]
jazz

**Comment by Alex-Coulon** [comment]
Tis wel duidelijk denk ik ;)

**Comment by Jazzkuh** [comment]
SWITCHEN VAN DARK NAAR LIGHTTHEME

**Comment by lokerhp** [comment]
dat willen wij

**Comment by LittleDraily** [comment]
jazz moeten we blind

**Comment by Jazzkuh** [comment]
> jazz moeten we blind

Ja

**Comment by TychoBlankvoort** [comment]
Schuifje
https://gyazo.com/fcd3f7943f6dfcf89367706a6b1806e5
