### ISSUE TITLE
Bankpas bugg

### ISSUE THREAD

**Issue by Marijn2341** [MinetopiaSDB/wiki#3]
Jowjow,

Ik wil hier even een bug melden.
De bankpas die je uit /ddgitems onder het kopje "items - 5" werkt niet.
Als je rechtermuisklik erop doet zie je je balance niet.

Ook staat hij er dubbel op, Hij staat 1 keer in "items -5" en 1 keer in "bruikbare items"

Ik stuur hieronder wel even een filmpje.

[KLIK HIER VOOR FILMPJE](https://cdn.discordapp.com/attachments/613445431040671764/718450853198954526/Minecraft_1.12.2___LabyMod_3.6.12_2020-06-05_15-05-40.mp4) <

**Comment by MrWouterNL** [comment]
Hoi, de wiki is geen plek om bugs te reporten! Dat mag gewoon in de supportkanalen.
